application: sintjanlommel2
version: 1
runtime: python
api_version: 1


handlers:
- url: /s
  static_dir: static
  
- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  script: main.py


builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
  
